django-2/myapp/urls.py
from django.urls import path
from . import views

app_name = "myapp"

urlpatterns = [
    path('', views.HomePage.as_view(),name="index"),
    path('<int:pk>/',views.PostDetailView.as_view(),name="detail"),
    path("new/",views.CreateNewPost.as_view(),name="new_post")
]










django-2/myproject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from myapp import urls as app_urls
from profiles import urls as profiles_urls
from django.conf.urls.static import static
from django.conf import settings




urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include(app_urls, namespace="myapp")),
    path("profile/", include(profiles_urls, namespace="profiles")),
    path("accounts/",include("allauth.urls")),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)




django-2/profiles/urls.py
from django.urls import path

from . import views

app_name = "profiles"

urlpatterns = [
    path("<str:username>/", views.PostDetailView.as_view(),name="detail"),
    path("<str:username>/follow/", views.FollowView.as_view(),name="follow"),

]

django-2/follower/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Follower(models.Model):
    followed_by = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name = 'followed_by'
    )
    following = models.ForeignKey(
        User,
        on_delete = models.CASCADE,
    )

django-2/myapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Post(models.Model):
    text= models.CharField(max_length=240)
    date = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    def __str__(self) -> str:
        return self.text[:20]

django-2/profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from sorl.thumbnail import ImageField

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete = models.CASCADE,
        related_name = "profiles"
    )
    image = ImageField(upload_to = 'profiles')
    
    def __str__(self) -> str:
        return self.user.username

@receiver(post_save,sender=User)
def create_user_profile(sender, instance,created,**kwargs):
    """Create a new Profile() oject when a Djago.User.is.created."""
    if created:
        Profile.objects.create(user=instance)

django-2/follower/views.py
from django.shortcuts import render

# Create your views here.

django-2/myapp/views.py
#from django.shortcuts import render
# Create your views here.
from typing import Any
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.http.request import HttpRequest as HttpRequest
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView
#CRUD
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Post

class HomePage(ListView):
    http_method_names = ["get"]
    template_name = "homepage.html"
    model = Post
    context_object_name = "posts"
    queryset = Post.objects.all().order_by('-id')[:30] 

class PostDetailView(DetailView):
    http_method_names=['get']
    template_name = "detail.html"
    model = Post
    context_object_name = "post"

class CreateNewPost(LoginRequiredMixin,CreateView):
    model=Post
    template_name="create.html"
    fields = ['text']
    success_url = '/'

    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        self.request = request
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.author = self.request.user
        obj.save()
        return super().form_valid(form)
    




django-2/profiles/views.py
from typing import Any
from django.contrib.auth.models import User
from django.http.request import HttpRequest as HttpRequest
from django.http.response import HttpResponse as HttpResponse
from django.views.generic import DetailView,View
from django.contrib.auth.mixins import LoginRequiredMixin

from django.http import JsonResponse,HttpResponseBadRequest
# Create your views here.
from myapp.models import Post
from follower.models import Follower

class PostDetailView(DetailView):
    http_method_names = ['get']
    template_name = "profiles/details.html"
    model = User
    context_object_name = "user"
    slug_field = "username"
    slug_url_kwarg = "username"
    
    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        self.request = request
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        user = self.get_object()
        context = super().get_context_data(**kwargs)
        context['total_post'] = Post.objects.filter(author=user).count()
        if self.request.user.is_authenticated:
            context['you_follow'] = Follower.objects.filter(following=user, follow_by=self.request.user).exists()
        return context

class FollowView(LoginRequiredMixin, View):
    http_method_names = ["post"]

    def post(self,request,*args,**kwargs):
        data = request.POST.dict()
        print("--------",data)
        if "action" not in data or "username" not in data:
            return HttpResponseBadRequest("Missing data.")
        try:
            other_user = User.objects.get(username=data(['username']))
        except User.DoesNotExist:
            return HttpResponseBadRequest("Missing data.")
        if data['action']=="follow":
            #follow
            follower,created=Follower.ojecects.get_or_create(
                followed_by = request.user,
                following = other_user
            )
        else:
            #unfollow
            try:
                follower = Follower.objects.get(
                    followed_by = request.user,
                    following = other_user,
                )
            except Follower.DoesNotExit:
                follower=None

        return JsonResponse({
            'done':True,
            'wording':"Unfollow" if data['action']=="follow" else "Unfollow"
        })

django-2/myapp/templates/create.html
{% extends "base.html" %}

{% block title %}Creat a new post{% endblock title %}
{% block body %}
    <form method="POST" action=".">
        {% csrf_token %}
        {{form.as_p}}
        <div>
            <form method="POST" action="."></form>
            <div class="my-3">
                <button class="h-8 px-4 m-2 text-sm text-indigo-100 transition-colors duration-150 bg-indigo-700 rounded-lg focus:shadow-outline hover:bg-indigo-800" type="submit">Create Post</button>
            </div>
        </div>
{% endblock body %}











django-2/myapp/templates/detail.html
{% extends "base.html" %}

{% block title %}{{post.text}} by {{post.author.username}}{% endblock %}

{% block body %} 

    {% include "include/post.html" with post=post %}
    
{% endblock body %}







django-2/myapp/templates/homepage.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}HomePage {% endblock %}

{% block body %}
    {% for post in posts %}
        {% include "include/post.html" with post=post show_detail_link=True %}
    {% endfor %}
    <img src="http://jaced.com/blogpix/2007/trisquarecircle/002.gif" usemap="#shapes">

    <map name="shapes">
        <area shape="polygon" coords="79,6,5,134,153,134"> polygon
        <area shape="rectangle" coords="177,6,306,134"> rectangle
        <area shape="circle" coords="397,71,65"> circle
    </map>
{% endblock %}











django-2/myproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Default title in here{% endblock %}</title>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css" />
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
  </head>
<body>

  <!-- component is from https://tailwindcomponents.com/component/sidebar-navigation -->
  <div class="min-h-screen flex flex-row bg-gray-100">
    <div class="flex flex-col w-56 bg-white rounded-r-3xl overflow-hidden">
      <div class="flex items-center justify-center h-20 shadow-md">
        <h1 class="text-3xl uppercase text-indigo-500">MY PROJECT</h1>
      </div>
      <ul class="flex flex-col py-4">
        <li>
          <a href="/" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
            <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class="bx bx-home"></i></span>
            <span class="text-sm font-medium">Home</span>
          </a>
        </li>
        {% if request.user.is_authenticated %}
          <li>
            <a href="{% url 'myapp:new_post' %}" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
            <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class="bx bxs-layer-plus"></i></span>
            <span class="text-sm font-medium">New Post</span>
            </a>
          </li>

          <li>
              <a href="{% url 'account_logout' %}" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
              <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class="bx bx-log-out"></i></span>
              <span class="text-sm font-medium">Logout</span>
              </a>
          </li>
          
        {% else %}
          <li>
              <a href="{% url 'account_login' %}" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
              <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class="bx bx-log-in"></i></span>
              <span class="text-sm font-medium">Login</span>
              </a>
          </li>
        {% endif %}
      </ul>
    </div>
    <div class="p-16">
      {% block body %}
          {% block content %}{% endblock %}
      {% endblock %}
    </div>
    


<!-- Main modal -->
<div id="static-modal" data-modal-backdrop="static" tabindex="-1" aria-hidden="true" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
    <div class="relative p-4 w-full max-w-2xl max-h-full">
        <!-- Modal content -->
        <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
            <!-- Modal header -->
            <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t dark:border-gray-600">
                <h3 class="text-xl font-semibold text-gray-900 dark:text-white">
                    New Post
                </h3>
                <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-hide="static-modal">
                    <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                    </svg>
                    <span class="sr-only">Close modal</span>
                </button>
            </div>
            <!-- Modal body -->
            <div class="p-4 md:p-5 space-y-4">
                <p class="text-base leading-relaxed text-gray-500 dark:text-gray-400">
                    With less than a month to go before the European Union enacts new consumer privacy laws for its citizens, companies around the world are updating their terms of service agreements to comply.
                </p>
                <p class="text-base leading-relaxed text-gray-500 dark:text-gray-400">
                    The European Union’s General Data Protection Regulation (G.D.P.R.) goes into effect on May 25 and is meant to ensure a common set of data rights in the European Union. It requires organizations to notify users as soon as possible of high-risk data breaches that could personally affect them.
                </p>
            </div>
            <!-- Modal footer -->
            <div class="flex items-center p-4 md:p-5 border-t border-gray-200 rounded-b dark:border-gray-600">
                <button data-modal-hide="static-modal" type="button" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">I accept</button>
                <button data-modal-hide="static-modal" type="button" class="ms-3 text-gray-500 bg-white hover:bg-gray-100 focus:ring-4 focus:outline-none focus:ring-blue-300 rounded-lg border border-gray-200 text-sm font-medium px-5 py-2.5 hover:text-gray-900 focus:z-10 dark:bg-gray-700 dark:text-gray-300 dark:border-gray-500 dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-gray-600">Decline</button>
            </div>
        </div>
    </div>
</div>

  </div>
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

django-2/myproject/templates/include/post.html


{% load thumbnail %}


<div class="max-w-4xl px-10 my-4 py-6 bg-white ronded-lg shadow-md" style="width: 50rem; margin: 10px;">
    <span class="font-light text-gray-600">{{post.date|date:"F j,Y, g:i:a"}}</span>
    <div class="mt-2">
        <p class="font-light text-gray-600">{{post.text}}</p>
    </div>
    <div class="flex justify-between items-center">
        {% if show_detail_link %}
            <a href="{% url 'myapp:detail' post.id %}" class="text-blue-600 hover:underline">Read more</a>
        {% else %}
            <a href="#">No details view</a>
            {% endif %}  
        <a class="flex items-center" href="{% url 'profiles:detail' post.author.username %}">
            {% thumbnail post.author.profiles.image "50x25" crop="center" as im %}
                <img src="{{ im.url }}" alt="AVATAR">
            {% endthumbnail %}
                <h1 class="text-gray-700 font-bold">{{post.author.username}}</h1>
        </a>
        
    </div>
</div>



django-2/profiles/templates/profiles/details.html
{% extends "base.html" %}

{% block body %}
{% load thumbnail %}
<div class="rounded rounded-t-lg overflow-hidden shadow max-w-xs my-3">
    <img src="http://i.imgur.com/dYcYQ7E.png" class="w-full" alt="hi1">
    <div class="flex justify-center -mt-8">
        {% thumbnail user.profiles.image "50x25" crop="center" as im %}
            <img src="{{ im.url }}" alt="AVATAR" class="rounded-full border-solid border-white border-2 -mt-3">
        {% endthumbnail %}
    </div>
    <div class="text-center px-5 pb-6 pt-2">
        <h1 class="text-black text-sm bold font-sans mt-3">{{user.username}}</h1>
        {% if request.user.is_authenticated %}
            {% if request.user != user %}
                <div class="my-3">
                    <button class = "h-8 px-4 m-2 text-sm text-indigo-100 transition-colors duration-150 bg-indigo-700 rounded-lg focus:shadow-outline hover:bg-indigo-800 js-follow" type="button" data-action="follow" data-url="{% url 'profiles:follow' user.username %}">
                        <span class="mr-2 js-follow-text">
                            {% if you_follow %}
                                Unfollow
                            {% else %}
                                Follow
                            {% endif %}
                        </span>
                        <svg xmlns="http://www.w3.org/2000/svg" width="200" height="24" viewBox="0 0 24 75">
                            <path fill="currentcolor" d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z"></path>
                        </svg>
                    </button>
                </div>
            {% endif %}
        {% else %}
            <div class="mt-3 text-sm">Login to follow this user</div>
        {% endif %}
        <p class="mt-3 font-sans font-lght text-grey-dark js-follow-text">Hello, i'm Dinesh Chandra</p>
    </div>
    <div class="flex justify-center pb-3 text-grey-dark">
        <div class="text-center mr-3 border-r pr-3">
            <h2>{{total_post}}</h2>
            <span>post</span>
        </div>
            
        <div class="text-center mr-3 border-r pr-3">
            <h2>xx</h2>
            <span>Followers</span>
        </div>
    </div>

</div>
{% endblock %}